### ISSUE TITLE
AndroidStudio freezed when edit pubspec.yaml

### ISSUE THREAD

**Issue by xiaozhizhong** [marius-h/flutter_enhancement_suite#37] opened 2020-03-11 10:03 UTC
When edit the pubspec.yaml, sometimes(not always) AS freezed for about 1 minute  when i  input or delete every letters. After I close the this plugin, it goes well.
I've tried it both on Mac and Windows.
I guess(not sure), it's something about the network block. I'm in china, and not use VPN.

**Comment by Prn-Ice** [comment] 2020-04-02 14:15
Same here

**Comment by marius-h** [comment] 2020-04-18 22:18
Have you already tried the plugin in another flutter app with a different pubspec.yaml?

**Comment by xiaozhizhong** [comment] 2020-04-20 01:22
> Have you already tried the plugin in another flutter app with a different pubspec.yaml?

Yes, I've tried it in a new created project which pubspec.yaml only have base flutter dependency,  and it's freezed all the same.

**Comment by marius-h** [comment] 2021-03-17 02:29
Quick note for me: I might have to use this api's url: https://pub.flutter-io.cn/api/packages/

**Comment by marius-h** [comment] 2021-03-25 22:33
Hey @xiaozhizhong @Prn-Ice 👋🏻  This issue *might* be fixed with update v1.5.0 which will be coming out in the next days. Unfortunately, I cannot verify if this actually fixes your problem as I was unable to reproduce your working environment in which these performance issues occurred. If you're still having issues with Android Studio freezing, I'll look into what else I can do.

**Closed** 2021-03-25 22:39 UTC
Labels: bug
