### ISSUE TITLE
java.lang.RuntimeException: de.mariushoefler.flutter_enhancement_suite.pub.UnableToGetLatestVersionException: Cannot get the latest version number for dependency: rxdart: ^0.24.1

### ISSUE THREAD

**Issue by feinstein** [marius-h/flutter_enhancement_suite#58] opened 2020-09-23 17:10 UTC
## What happened

I have no idea, just got an error message.

## Version information

IntelliJ IDEA `2020.2.2` • Flutter plugin `io.flutter 49.0.4` • Dart plugin `202.7319.5`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.RuntimeException: de.mariushoefler.flutter_enhancement_suite.pub.UnableToGetLatestVersionException: Cannot get the latest version number for dependency: rxdart: ^0.24.1
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:101)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:266)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:191)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: de.mariushoefler.flutter_enhancement_suite.pub.UnableToGetLatestVersionException: Cannot get the latest version number for dependency: rxdart: ^0.24.1
	at de.mariushoefler.flutter_enhancement_suite.pub.DependencyChecker.getLatestVersion(DependencyChecker.kt:46)
	at de.mariushoefler.flutter_enhancement_suite.utils.FileParser.mapToVersionDescription(FileParser.kt:59)
	at de.mariushoefler.flutter_enhancement_suite.utils.FileParser.access$mapToVersionDescription(FileParser.kt:13)
	at de.mariushoefler.flutter_enhancement_suite.utils.FileParser$Companion$getVersionsFromFile$$inlined$map$lambda$1.invokeSuspend(FileParser.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by marius-h** [comment] 2021-03-01 22:08
I've done some changes to the way the dependency checker works which might have fixed your issue. As I can't reproduce the issue, I'll close it for now. Feel free to reopen it if you're still fighting with this issue on the upcoming version

**Closed by marius-h** 2021-03-01 22:08 UTC
Labels: bug
