### ISSUE TITLE
KotlinNullPointerException when creating a new Flutter project (application)

### ISSUE THREAD

**Issue by dabo248** [marius-h/flutter_enhancement_suite#8] opened 2019-08-18 20:33 UTC
**Describe the bug**

I created a new project with File -> New -> Project and while creation the exception occurred.

**Steps to Reproduce**

Creating a new project with File -> New -> Project. On creation the mentioned exception occurs (happened two out of three times).

**Screenshots**

<img width="807" alt="Bildschirmfoto 2019-08-18 um 22 16 28" src="https://user-images.githubusercontent.com/11370593/63229985-fbb44b00-c206-11e9-9564-2ac77c33aa19.png">

**Software used**

```
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
```

**Comment by marius-h** [comment] 2019-08-18 20:45
Duplicate of #5

**Closed by marius-h** 2019-08-18 20:45 UTC
Labels: bug
