### ISSUE TITLE
UI freezes when checking for package updates

### ISSUE THREAD

**Issue by athornz** [marius-h/flutter_enhancement_suite#20] opened 2019-10-09 20:38 UTC
When the plugin checks for package updates (when first opening the pubspec for example) the UI can freeze for a long time, sometimes up to 30-40 seconds.

I investigated and fixed this issue in the FlutterPubVersionChecker plugin: https://github.com/pszklarska/FlutterPubVersionChecker/pull/8

What do you think of this approach?

**Comment by marius-h** [comment] 2019-10-09 21:50
Thanks for pointing this out. I will change the version checking to run on coroutines in the next version.

**Comment by shinayser** [comment] 2019-12-02 15:11
Hey, do you have a ETA on when we getting this release? The plugin is AMAZING but this freeze sometimes is very annoying because it freezes the entire IDE.

**Comment by marius-h** [comment] 2019-12-29 01:35
@shinayser I'll probably release an update next week 😄 The issue is fixed now.

**Closed by marius-h** 2019-12-29 01:35 UTC
Labels: bug
